---
- hosts: all
  become: true
  vars:
    username:
        - Rens S. Espano
  tasks:

  - name: Install python3 and pip3 in Ubuntu and CentOS
    package:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes

  - name: Set pip3 as default pip  in Ubuntu and CentOS
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "CentOS")

  - name: Set python3 as default python in Ubuntu and CentOS
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "CentOS")

  - name: Install Java openJDK in Ubuntu and CentOS
    package:
      name:
        - "{{ java_package }}"
      state: latest
      update_cache: yes

  - name: Create MOTD Banner
    template:
       src: motd.j2
       dest: /etc/motd

  - name: Create a User
    user:
     name: "username"
